fluidkeys/api

README.md
v1structs/structs.go

We don't actually support any `contentType` other than `text/plain` so
don't include it.

Add more structs to v1structs, delete contentType

---

.travis.yml

It's not postgres 10 (which we're using on heroku) but it's the nearest I
can get without it being a PITA.
See
https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version
And https://github.com/travis-ci/travis-ci/issues/8537
also, don't install dep (we're not using it)

travis: use postgresql 9.6 from addons

---

Gopkg.lock
datastore/datastore.go
server/secretshandler.go
server/server_test.go
vendor/github.com/fluidkeys/fluidkeys/fingerprint/fingerprint.go

* datastore.CreateSecret: fail nicely if missing fpr
If there's no key for the given fingerprint, return a nice error rather
than just giving a foreign key constraint error from postgresql
* bump fluidkeys/fingeprint for Fingerprint.Uri()

add tests for secret send (and lots of fixes!)

---

Gopkg.lock
datastore/datastore.go
datastore/schema.go
server/encrypt.go
server/json.go
server/keyshandler.go
server/secretshandler.go
server/server.go
server/server_test.go
vendor/github.com/fluidkeys/crypto/openpgp/clearsign/clearsign.go

* update v1structs for upsert public key endpoint
* verify(..) function for clearsigned data
* factor out decodeJsonRequest function
* add datastore single use UUID table & funcs
* add github.com/fluidkeys/crypto/openpgp/clearsign

upsert public key endpoint & tests

---

.realize.yaml

use "api" as the `name`, not the full path

fix realize output

---

.travis.yml
email/email.go
email/email_test.go
server/keyshandler.go
vagrant/bashrc

* new database table email_verifications
* logic to decide if an upserted public key should get any verification emails
* code for rendering a verification email
* code for *sending* verification emails
for development you can set DISABLE_SEND_EMAIL=1 (included in vagrant bashrc)

Send verification emails on public key upsert

---

server/keyshandler.go
server/server_test.go

* add tests for (existing) /v1/email/<email>/key.asc
retrofit them since they didn't exist already
* factor out assertBodyEqualTo

Factor out duplicate code from get-key-by-email handlers

---

datastore/datastore.go
datastore/schema.go
server/server_test.go

rebase after #24
we use the postgres citext (case insensitive text) extension to *query* in
a case insensitive way, while *storing* with the original case.

case-insensitive search on email addresses

---

datastore/schema.go

so that it's impossible to have 2 requests for the same email to join a
given team.

add unique(team_uuid, email) constraint in db

---

server/teamshandler.go
server/teamshandler_test.go

we introduced the concept of `is_admin` in the roster, and this check
reflects that.
when uploading a roster, the key that signed the roster should be listed in
the roster *as an admin*

createHandler: check signer in roster is an admin

---

datastore/team.go
datastore/team_test.go
server/listrequeststojointeamhandler_test.go
server/teamshandler.go
server/teamshandler_test.go

allow the datastore to update a team's roster and roster signature.
note that the CreatedAt field is *not* updated :)

datastore: CreateTeam -> UpsertTeam

---

server/server.go
server/teamshandler.go
v1structs/v1structs.go

* v1structs: add GetTeamRosterResponse
* factor out `TeamRosterAndSignature` so it can be used by both
`GetTeamRosterResponse` and `UpsertTeamRequest`
note that `UpsertTeamRequest` is now defind with
`TeamRosterAndSignature` as an embedded type, meaning the latter's
fields are available directly through `UpsertTeamRequest`

add placeholder "get team roster" endpoint

---

datastore/datastore.go
datastore/datastore_test.go
datastore/schema.go
server/listrequeststojointeamhandler_test.go
server/server_test.go
server/teamshandler_test.go
server/verifyhandler.go

When we create a new row in `email_key_link` (via LinkEmailToFingerprint),
record the UUID of the associated `email_verification` row.
* LinkEmailToFingerprint: also take a verificationUUID
* GetVerification: return a `EmailVerification` struct (which contains
the UUID) rather than `email`, `fingerprint`
* db schema: link email_key_link back to email_verification_uuid
* db migration: populate `email_verification_uuid` for all existing rows in 
`email_key_link`

LinkEmailToFingerprint: record email_verification

---

email/email.go

emailTemplateInterface is used to define a struct represeneting a specific type of email, for
example help_key_expires_3_days

add emailTemplateInterface

---

datastore/emailqueries.go
datastore/emailqueries_test.go

canSendWithRateLimit looks up the last time we sent a given (user profile +
email template) combination in the database, and returns whether we're past
the given rateLimit duration.
For example, if we want to ensure we don't send `template_1` to `profile_1`
more than once per hour, we could use it like this:
> canSendWithRateLimit(profile_1, template_1, time.Duration(1) * time.Hour)
note that a rateLimit of `nil` means *unlimited* and will always return
true. *use with care!*
for emails intended to be sent only once (e.g. onboarding emails), consider
using 1 year. this way, we avoid completely stale information, and the
person will get an (infrequent) reminder that we still hold their
information, giving them an opportunity to ask us to delete it.

datastore.CanSendWithRateLimit

---

Makefile
cmd/sendemails/sendemails.go
email/email.go
email/helpkeyexpires.go
email/sendfromcron.go

* add SendKeyExpiresEmails, call from sendemails
this sends 3-day expiry reminders.
call it from `email/sendfromcron` (which is in turn called from
`cmd/sendemails/sendemails.go`)
* add sendEmail helper function
this is a generic helper function which takes an email template (a struct
implemeting the emailTemplateInterface) and:
* checks the rate-limit to see if it's OK to send this type of email again
* lets the template render the email (using new
emailTemplateInterface.RenderInto)
* sends the email
* records that it was sent

Email keys expiring in 3 days

---

email/email.go
email/email_test.go
email/helpkeydeleted.go
email/helpkeyexpires.go
email/render.go

so that we're prepared to render plaintext emails as text, not HTML
Also, use renderText for the verification email subject, fixing this
bug:
https://trello.com/c/R2uR1hEk

rename render -> renderHTML, add renderText

---

cmd/sendtestemails.go
email/email.go
email/email_test.go
email/helpkeydeleted.go
email/helpkeyexpires.go
email/render.go
email/sendtestemails.go
main.go

* add command: send_test_emails <email>
this allows us to test sending text and HTML emails from production
* email.send: support plain email body
* verify & deleted email: populate `textBody` not `htmlBody`

render & send text emails as text, not HTML

---

server/teamshandler.go
server/teamshandler_test.go

if someone requests to join a team with exactly the same information, just return `OK`

treat identical request to join as OK

---

server/errors.go
server/listrequeststojointeamhandler.go
server/listrequeststojointeamhandler_test.go
server/teamshandler.go

previously, the list requests endpoint checked whether *I had signed the
roster*. That's no good because it only allows for one admin!
Instead, check whether I'm an admin of the team.
Fixes https://trello.com/c/9cF2ajFW

list requests: check I am a team admin

---

Makefile

it makes it really hard to see which test failed, as the failure gets
followed by loads more test output

`make test`: don't run tests verbosely

---

Gopkg.lock
Gopkg.toml
server/teamshandler_test.go
vendor/github.com/fluidkeys/fluidkeys/policy/policy.go
vendor/github.com/fluidkeys/fluidkeys/team/team.go
vendor/github.com/fluidkeys/fluidkeys/team/validateupdate.go

* bump `fluidkeys/fluidkeys` dependency to get version of `Team` struct which includes `Version`
* tests: ensure with / without version is OK. this is to ensure the endpoint can accept rosters with the new `version` field *and* rosters where the field is missing (older versions of `fk`)
It *should* be OK to merge and deploy this without breaking old versions of `fk` that don't send a `version`. (This would be an excellent thing to verify!)

support "version" field in team endpoint
