datastore/datastore.go, server/secretshandler.go, server/server.go
* add deleteSecretHandler
* set url route for delete secret
* it's strict about the format of a UUID
* add datastore.DeleteSecret
* factor out dbFormat(fingerprint)
=> add deleteSecretHandler

datastore/datastore.go, server/server_test.go
* add datastore.DeletePublicKey
=> make setup/teardown funcs for send secret test

datastore/datastore.go, server/secretshandler.go, server/server_test.go
* datastore.CreateSecret: return secretUUID
=> add tests for list secrets endpoint

vagrant/bashrc, vagrant/provision.sh
https://github.com/kyoh86/richgo
Just use `make test` inside vagrant
=> colour test output with `richgo`

datastore/datastore.go, datastore/schema.go
* CreateVerification
* HasActiveVerificationForEmail
=> datastore: add email verifications

server/keyshandler.go, server/server.go
So I can finally redirect paulfurley.com/pgp to it :)
=> add /v1/email/<email>/key.asc endpoint

server/keyshandler.go, server/server.go, server/server_test.go
* `/v1/key/<fingerprint>`
* `/v1/key/<fingerprint>.asc`
where fingerprint is of the form A999B7498D1A8DC473E53C92309F635DAD1B5517
=> add endpoints to get key by fingerprint

cmd/migrate/migrate.go, datastore/datastore.go, server/keyshandler.go, server/secretshandler.go, server/server.go, server/server_test.go
they hide my actual compiler issues in vim which makes it awkward to spot them
* fix if { return } / else lint issues
* comment import rename to _
* datastore: add comments to exported functions
* don't end error message with punctuation
* rename to uppercase versions
=> fix golint issues

server/server_test.go
* add testEndpointRejectsBadJSON, use in endpoints
for endpoints that expect JSON input, factor out a common set of tests to
ensure they reject bad JSON
* add authFingerprint to callAPIWithJSON
... so we can make test requests to the API, authenticated by the public
=> improve test helpers

datastore/datastore.go, datastore/datastore_test.go, datastore/schema.go, datastore/team.go, datastore/team_test.go
* GetTeam
* DeleteTeam
* CreateTeam
* TeamExists
=> add datastore team methods & tests

server/server.go, server/teamshandler.go
@idrysdale mostly for you to look at the routes!
=> add placeholder endpoints for requests to join team

server/teamshandler.go, server/teamshandler_test.go
=> add get team endpoint

Gopkg.lock, Gopkg.toml, server/teamshandler_test.go, vendor/github.com/fluidkeys/fluidkeys/exampledata/exampledata.go, vendor/github.com/fluidkeys/fluidkeys/fingerprint/fingerprint.go, vendor/github.com/fluidkeys/fluidkeys/pgpkey/pgpkey.go, vendor/github.com/fluidkeys/fluidkeys/team/team.go
* add is_admin to roster tests
=> bump fluidkeys dep, bring in is_admin in roster

server/teamshandler.go, server/teamshandler_test.go
convenience function to:
1. load the team in database format (string roster)
2. parse the roster into a team.Team
and pass through errors, if any
=> factor out loadExistingTeam

server/teamshandler.go, server/teamshandler_test.go
rebase after #50 #51 #52
in the case of a team *update* (the team already exists), we need to check
that the person who signed the new roster *was an admin* of the old team,
not just an admin of the new team!
- is the requester (who signed the roster) listed in the *existing*
team as an admin?
- would the admin be demoting themselves? (not OK)
=> upsert team: allow team admins to update the team

server/teamshandler.go, server/teamshandler_test.go
this will return the (encrypted) roster for the given team, as long as
you're listed as being in the team.
=> add /team/:uuid/roster endpoint

server/listrequeststojointeamhandler_test.go, server/server_test.go, server/teamshandler.go, server/teamshandler_test.go
just make `callAPI` accept a third argument (`requestData`) which will be
converted to JSON. if it's `nil`, it won't be.
=> combine `callAPIWithJSON` with `callAPI`

server/listrequeststojointeamhandler_test.go, server/server_test.go, server/teamshandler_test.go
I've added or checked these endpoints:
These endpoints don't return JSON (usually because they don't return
anything at all):
* pingHandler
* verifyEmailHandler
* getASCIIArmoredPublicKeyByEmailHandler
* getASCIIArmoredPublicKeyByFingerprintHandler,
* upsertTeamHandler,
* createRequestToJoinTeamHandler,
* deleteRequestToJoinTeamHandler,
* sendSecretHandler
* deleteSecretHandler
=> test all JSON endpoints return application/json

datastore/team.go, datastore/team_test.go, server/teamshandler.go, server/teamshandler_test.go
Requires https://github.com/fluidkeys/api/pull/59
=> Implement deleteRequestToJoinTeamHandler

vagrant/bashrc
since it doesn't seem to pass through arguments correctly
=> don't alias go=richgo (for colour)

.gitignore, script/dump_production_database
=> add script/dump_production_database

datastore/schema.go
these are *furiously minimal* for now
=> db: add tables user_profiles, emails_sent

datastore/schema.go, datastore/user_profile.go, datastore/user_profile_test.go
=> loadUserProfile, createUserProfile, UserProfile

datastore/emailqueries.go, datastore/emailqueries_test.go
* datastore.RecordSentEmail
this lets you store that a given type of email (email template) was sent to
a user profile
* datastore.GetTimeLastSent
this lets you look up the last time we sent a specific email template to a
given user profile
=> datastore: RecordSentEmail, GetTimeLastSent

datastore/emailqueries.go
this finds all (verified) keys with an expiry in the next 15 days
=> add datastore.ListKeysExpiring

cmd/printexpiredkeys/printexpiredkeys.go, datastore/emailqueries.go
instead of simply returning a key, return a list of verified and
unverified email addresses too
this is in preparation for make delete_expired_keys which will actually
email the person and delete their key
=> improve ListExpiredKeys

.gitignore, Makefile, cmd/deleteexpiredkeys/deleteexpiredkeys.go, cmd/printexpiredkeys/printexpiredkeys.go, datastore/emailqueries.go, email/helpkeydeleted.go
This iterates through all expired keys, sending an email then deleting them
from the database.
=> add `make delete_expired_keys`

server/eventhandler.go, server/server.go, v1structs/v1structs.go
this allows the API to receive log events from fk
v1structs: add CreateEventRequest
=> add (placeholder) /events handler
